### PR TITLE
Make error handling more tolerant.

### PR DESCRIPTION
**Pull request by KickerTom**
In case of inaccessible files (e.g. ".android_secure" on SD card), adb commands return error (permission denied) as part of directory listing. Current code chokes on this and returns empty folder. My changes will list the whole folder, even with the inaccessible file (albeit always as empty regular file with all right revoked).

### CODE REVIEW

**Comment by IzzySoft** [comment]
I've just tested this patch. Fixes issue #11 along the lines – so:

Please go ahead @spion
and catch 2 birds with one stone :)

**Comment by IzzySoft** [comment]
Ooops – side-effects! @KickerTom not sure what part of your changes is causing that, but when I try entering a directory I have no permissions to (e.g. one owned by `root:root` and `0700`), `adbfs` hangs with 100% CPU until killed with `SIGKILL` (!) I don't remember that from before. Could you please cross-check?

**Comment by KickerTom** [comment]
Fixed, my fault, sorry for that. I need to be more careful next time with constructs like "continue" :-).

**Comment by IzzySoft** [comment]
That's perfect. I thought about the same: but showing "empty" seems the best compromise (except for "popping up an error" which isn't working in our case) – as "doing nothing" would get confusing e.g. with graphical file managers ("did I miss the icon or what?!? Is my mouse buggy – or the app frozen?"). At least that's a little feedback.

If a directory is empty because I have no permissions to enter it, that's something I can live with. But if it *seems* empty because it holds, amongst many others, just 1 file (`.android_secure`) I have no permission to see – that's something hard to figure. If I hadn't seen your patch I'd spent another day to find out (I initially suspected a bug in my ROM/ADB (and played with its settings), then that stupid SD-Card restriction introduced with KK (and toyed with that) – I never had guessed the real reason).

So thanks, good job! I'll test it again when I'm back at my machine tonight – but if you simply added those 3 lines (plus maybe some "whitespaces" around) directly in front of the loop, that's what I've tested last night already, and it should be fine to go (pointer for @spion for the merge).

**Comment by spion** [comment]
I've got almost no time to review this, but you can get a whitespaceless github diff using ?w=1 e.g. https://github.com/spion/adbfs-rootless/pull/10/files?w=1

I'll try to find some time to look at it tomorrow...

**Comment by IzzySoft** [comment]
@spion I just did a quick check (all the places where I had issues before). Looks good so far:

* directory with `.android_secure` shown incl. content
* directories I shouldn't have access to turn up empty (instead of causing an infinite loop at 100% CPU usage)
* pull/read of some picked examples worked fine
* output from `adbfs -f` (running in a separate window) looks clean, nothing unexpected, no errors spotted

So I agree it should be fine. Another look doesn't hurt if you find time (everone points his eyes at different angles) – but if not, just merge it. If something is spotted later we can fix it then :)

Thanks for the `w=1` pointer – learned a piece again :)

**Pull request merged**
